# experiment params
NUM_SEEDS: 1
SEED: 0

# if  hyperparameters tuning
HYP_TUNE: True

# wandb params
WANDB_MODE: "online"  # set to online to activate wandb
ENTITY: "2002stefanrares-university-of-groningen"
PROJECT: "PQN-Bachelors"
alg:
  WANDB_LOG_ALL_SEEDS: False # will log all the vmapped seeds separetely

# where to save the params (if None, will not save)
SAVE_PATH: "./models"
