# this is adapted from Atari configuration (with a slightly higher exploration eps), may get better results with some tuning
ALG_NAME: "pdqn"
TOTAL_TIMESTEPS: 1e7
TOTAL_TIMESTEPS_DECAY: 1e7 # will be used for decay functions, in case you want to test for less timesteps and keep decays same
NUM_ENVS: 128 # parallel environments
NUM_STEPS: 32 # steps per environment in each update
EPS_START: 1.
EPS_FINISH: 0.05
EPS_DECAY: 0.1 # ratio of total updates

EPS_START_PLAN: 1.0
EPS_FINISH_PLAN: 0.75
EPS_DECAY_PLAN: 0.0001

NUM_MINIBATCHES: 32 # minibatches per epoch
NUM_EPOCHS: 2 # minibatches per epoch
NORM_TYPE: "layer_norm" # layer_norm or batch_norm
LR: 0.0005
MAX_GRAD_NORM: 10
LR_LINEAR_DECAY: True
GAMMA: 0.99
LAMBDA: 0.65
PLANNING_STEPS: 10

# env specific
#ENV_NAME: "Asterix-MinAtar"
#ENV_NAME: "Breakout-MinAtar"
#ENV_NAME: "Freeway-MinAtar"
ENV_NAME: "SpaceInvaders-MinAtar"
ENV_KWARGS: {}

# evaluation
TEST_DURING_TRAINING: True 
TEST_INTERVAL: 0.05 # in terms of total updates
TEST_NUM_ENVS: 128
EPS_TEST: 0. # 0 for greedy policy
